typdef enum states {
	IDLE, MOVING_UP, MOVING_DOWN, OPEN, EMERGENCY
};

int queue[HARDWARE_NUMBER_OF_FLOORS][3]; /*= {
	{BUTTON_UP1, BUTTON_DOWN1, BUTTON_COMMAND1},
	{BUTTON_UP2, BUTTON_DOWN2, BUTTON_COMMAND2},
	{BUTTON_UP3, BUTTON_DOWN3, BUTTON_COMMAND3},
	{BUTTON_UP4, BUTTON_DOWN4, BUTTON_COMMAND4}
};*/

int light_matrix[HARDWARE_NUMBER_OF_FLOORS][3] = {
	{LIGHT_UP1, LIGHT_DOWN1, LIGHT_COMMAND1},
	{LIGHT_UP2, LIGHT_DOWN2, LIGHT_COMMAND2},
	{LIGHT_UP3, LIGHT_DOWN3, LIGHT_COMMAND3},
	{LIGHT_UP4, LIGHT_DOWN4, LIGHT_COMMAND4},
};

static const int order_types_array[3] = {
	{HARDWARE_ORDER_UP, HARDWARE_ORDER_DOWN,HARDWARE_ORDER_INSIDE}
};